### ISSUE TITLE
Better Formatting of Text on Speaker Cards

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#168]
There's gotta be a better way:

@bluedrops and @vpahwa  have had initial talks, but we're open to suggestons

<img width="309" alt="screen shot 2016-09-13 at 12 50 49 am" src="https://cloud.githubusercontent.com/assets/5349493/18462980/3afbafb2-794c-11e6-9031-b87514d7b69e.png">

**Comment by vpahwa** [comment]
Maybe an accordion of sorts? Like the white part slides down or something?

**Comment by bluedrops** [comment]
The accordion was the original plan, which I worked on; it was abandoned because having the white part 'slide down' would literally displace elements and break the column layout :')

Then I looked into a 'card flip' animation, but it wouldn't be supported on all browsers. Eventually it settled on the slide animation, which is supported by basically everything.

Also, I may be wrong but I think Sujay might be talking about the stylization/formatting of the bio text itself, since it's just an ugly block as it currently stands

**Comment by bluedrops** [comment]
I'm really bad at text stylization so someone please help :(

**Comment by vpahwa** [comment]
Achal said he'll take a look tomorrow. The accordion was his suggestion too

**Comment by sameetandpotatoes** [comment]
Not sure if this issue is marked as done or not, but making the first letter a bigger size could make the paragraph a bit clearer and less like a blob of text:

<img width="350" alt="screen shot 2016-09-19 at 7 26 13 pm" src="https://cloud.githubusercontent.com/assets/3608224/18653364/f62b2766-7e9e-11e6-8cd1-aee2de27a35a.png">

**Comment by sskhandek** [comment]
That's a good idea @sameetandpotatoes :)

**Comment by vgvbach95** [comment]
What about highlighting key words with the bold.

**Comment by vgvbach95** [comment]
Here is my proposed list of changes: try to shorten some of the bios, increase font size. If that doesn't work, then we may need to do a pop-out or something.

**Comment by vgvbach95** [comment]
Pull request submitted. I used similar changes to those on the speaker posters.
